CREATE TABLE IF NOT EXISTS T_users (
    F_id TEXT PRIMARY KEY AUTOINCREMENT,
    F_username TEXT NOT NULL,
    F_email TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS T_item (
    F_id TEXT PRIMARY KEY AUTOINCREMENT,
    F_name TEXT NOT NULL,
    F_description TEXT,
    F_imgPass TEXT
);